apiVersion: krakend.nais.io/v1
kind: ApiEndpoints # Note: to be applied in gcp, dev-fss-pub.nais.io endpoint gives a krakend entrypoint at https://<MY-TEAM>-gw.ekstern.dev.nav.no
metadata:
  name: sf-arkiv
  namespace: teamcrm
  labels:
    team: teamcrm
spec:
  appName: sf-arkiv
  auth:
    name: azuread
    cache: true
    audience:
      - "0ec61090-ae9a-4e22-8807-19323001855d"  # dev fetch from pod AZURE_APP_CLIENT_ID
  endpoints:                                    # specify your API endpoints requiring auth here
    - path: /sf-arkiv/arkiv                     # path for your API endpoint in KrakenD - must be unique within your namespace
      method: POST
      forwardHeaders:                           # if your backend validates tokens, you need to forward the Authorization header
        - Authorization
      backendHost: https://sf-arkiv-dokumentasjon.dev-fss-pub.nais.io        # the service url or ingress for your app
      backendPath: /arkiv                            # the path to your API endpoint in your app
    - path: /sf-arkiv/hente                   # path for your API endpoint in KrakenD - must be unique within your namespace
      method: POST
      forwardHeaders:                           # if your backend validates tokens, you need to forward the Authorization header
        - Authorization
      backendHost: https://sf-arkiv-dokumentasjon.dev-fss-pub.nais.io       # the service url or ingress for your app
      backendPath: /hente                            # the path to your API endpoint in your app
  openEndpoints:                                               # specify your open API endpoints here
    - path: /sf-arkiv/authping
      method: GET
      forwardHeaders: # if your backend validates tokens, you need to forward the Authorization header
        - Authorization
      backendHost: https://sf-arkiv-dokumentasjon.dev-fss-pub.nais.io
      backendPath: /authping