apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-arkiv
  namespace: teamcrm
  labels:
    team: teamcrm
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "256M"
spec:
  image: '{{ image }}'
  port: 8080
  replicas:
    min: 3
    max: 3
  liveness:
    path: /internal/is_alive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  preStopHook:
    exec:
      command: [ "/bin/bash", "/pre-stop.sh" ]
  resources:
    limits:
      memory: 3Gi
    requests:
      cpu: 100m
      memory: 512Mi
  prometheus:
    enabled: true
    path: /internal/prometheus
  ingresses:
    - "https://sf-arkiv-dokumentasjon.dev.intern.nav.no"
    - "https://sf-arkiv-dokumentasjon.dev-fss-pub.nais.io"
  vault:
    enabled: true
  webproxy: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: itestapp
          namespace: teamcrm
          cluster: dev-gcp
        - application: salesforce
          namespace: teamcrm
          cluster: dev-external
  env:
    - name: KTOR_ENV
      value: dev
    - name: MS_BETWEEN_WORK
      value: '600000'
    - name: MOUNT_PATH
      value: /postgresql/preprod-fss
    - name: DB_NAME
      value: arkiv-dokumentasjon
    - name: DB_ROLE
      value: admin
    - name: DB_URL
      value: jdbc:postgresql://b27dbvl023.preprod.local:5432/arkiv-dokumentasjon