apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-arkiv
  namespace: teamcrm
  labels:
    team: teamcrm
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "256M"
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /is_alive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  preStopHook:
    exec:
      command: [ "/bin/bash", "/pre-stop.sh" ]
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
    - "https://sf-arkiv-dokumentasjon.dev.intern.nav.no"
  vault:
    enabled: true
  webproxy: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: salesforce
          namespace: teamcrm
          cluster: dev-external
  kafka:
    pool: nav-dev # enum of nav-dev, nav-prod
  env:
    - name: KTOR_ENV
      value: dev
    - name: MS_BETWEEN_WORK
      value: '600000'
    - name: VAULT_INSTANCE
      value: PREPROD
    - name: MOUNT_PATH
      value: /postgresql/preprod-fss
    - name: DB_NAME
      value: arkiv-dokumentasjon
    - name: DB_ROLE
      value: admin
    - name: DB_URL
      value: jdbc:postgresql://b27dbvl023.preprod.local:5432/arkiv-dokumentasjon
    - name: KAFKA_CLIENTID
      value: arkiv-dokumentasjon
    - name: KAFKA_SECURITY
      value: 'TRUE'
    - name: KAFKA_SECPROT
      value: SASL_SSL
    - name: KAFKA_SASLMEC
      value: PLAIN
    - name: KAFKA_TOPIC
      value: personoversikt.henvendelse-henvendelse
    - name: MS_BETWEEN_WORK
      value: '600000'
    - name: VAULT_INSTANCE
      value: GCP