apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-arkiv
  namespace: teamcrm
  labels:
    team: teamcrm
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "256M"
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 3
    max: 4
  liveness:
    path: /is_alive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 1Gi
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
    - "https://sf-arkiv-dokumentasjon.intern.nav.no"
  vault:
    enabled: true
  webproxy: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
  accessPolicy:
    inbound:
      rules:
        - application: salesforce
          namespace: teamcrm
          cluster: prod-external
  kafka:
    pool: nav-prod # enum of nav-dev, nav-prod
  env:
    - name: KTOR_ENV
      value: production
    - name: MS_BETWEEN_WORK
      value: '600000'
    - name: VAULT_INSTANCE
      value: PRODUCTION
    - name: MOUNT_PATH
      value: /postgresql/prod-fss
    - name: DB_NAME
      value: arkiv-dokumentasjon
    - name: DB_ROLE
      value: admin
    - name: DB_URL
      value: jdbc:postgresql://A01DBVL022.adeo.no:5432/arkiv-dokumentasjon
    - name: KAFKA_CLIENTID
      value: arkiv-dokumentasjon
    - name: KAFKA_SECURITY
      value: 'TRUE'
    - name: KAFKA_SECPROT
      value: SASL_SSL
    - name: KAFKA_SASLMEC
      value: PLAIN
    - name: KAFKA_TOPIC
      value: personoversikt.henvendelse-henvendelse
    - name: MS_BETWEEN_WORK
      value: '600000'
    - name: VAULT_INSTANCE
      value: GCP