apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-arkiv
  namespace: teamcrm
  labels:
    team: teamcrm
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "256M"
spec:
  image: '{{ image }}'
  port: 8080
  replicas:
    min: 3
    max: 4
  liveness:
    path: /internal/is_alive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  preStopHook:
    exec:
      command: [ "/bin/bash", "/pre-stop.sh" ]
  resources:
    limits:
      memory: 3Gi
    requests:
      cpu: 10m
      memory: 512Mi
  prometheus:
    enabled: true
    path: /internal/prometheus
  ingresses:
    - "https://sf-arkiv-dokumentasjon.intern.nav.no"
    - "https://sf-arkiv-dokumentasjon.prod-fss-pub.nais.io"
  vault:
    enabled: true
  webproxy: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
  accessPolicy:
    inbound:
      rules:
        - application: itestapp
          namespace: teamcrm
          cluster: prod-gcp
        - application: saas-proxy
          namespace: teamcrm
          cluster: prod-gcp
        - application: sf-arkiv-proxy
          namespace: teamcrm
          cluster: prod-gcp
        - application: salesforce
          namespace: teamcrm
          cluster: prod-external
  env:
    - name: CONTEXT
      value: PROD
    - name: KTOR_ENV
      value: production
    - name: MS_BETWEEN_WORK
      value: '600000'
    - name: MOUNT_PATH
      value: /postgresql/prod-fss
    - name: TARGET_DB_NAME
      value: sf-arkiv
    - name: TARGET_DB_URL
      value: jdbc:postgresql://A01DBVL037.adeo.no:5432/sf-arkiv
